name: Build

#プルリクエスト作成時に実行(他にもpush時など設定できます)
on: [pull_request]

jobs:
  setup_and_test_execution:
#ubuntu環境で動かします
    runs-on: ubuntu-latest

#GitHub Actionsでサポートしているrubyのversionは2.6系以降です
    steps:
    - uses: actions/checkout@v1
    - name: Setup Ruby version 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.5

#MySQLをインストール
    - name: Install dependent libralies
      run: sudo apt-get install libmysqlclient-dev

    - name: Setup bundler
      run: gem install bundler

    - name: bundle install
      run: |
        bundle install --jobs 4 --retry 3

#test用に用意したdatabase.yml.ciをコピー、テスト環境用のDBを作成
    - name: Setup Database
      run: |
        cp config/database.yml.ci config/database.yml
        bundle exec rake db:create
        bundle exec rake db:schema:load
      env:
        RAILS_ENV: test

    - name: Run RSpec
      run: bundle exec rspec
      env:
        RAILS_ENV: test
