name: Ruby

# masterブランチへのPR時の実行
on: [pull_request]
jobs:
  setup_and_test_execution:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.5
      
    - name: Install dependent libralies
      run: sudo apt-get install libmysqlclient-dev

    - name: Setup bundler
      run: gem install bundler

    - name: bundle install
      run: |
        bundle install --jobs 4 --retry 3
        
    - name: Setup Database
      run: |
        cp config/database.yml.ci config/database.yml
        bundle exec rake db:create
        bundle exec rake db:schema:load
      env:
        RAILS_ENV: test

    - name: Run RSpec
      run: bundle exec rspec
      env:
        RAILS_ENV: test
